-- Create consultation_recordings table for storing recording metadata
CREATE TABLE IF NOT EXISTS consultation_recordings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  consultation_id UUID NOT NULL REFERENCES consultations(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL UNIQUE,
  file_size BIGINT NOT NULL,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_consultation_recordings_consultation_id 
ON consultation_recordings(consultation_id);

CREATE INDEX IF NOT EXISTS idx_consultation_recordings_recorded_at 
ON consultation_recordings(recorded_at DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE consultation_recordings ENABLE ROW LEVEL SECURITY;

-- Create policy: Admins and faculty can view recordings of their consultations
CREATE POLICY "Enable read access for authorized users" ON consultation_recordings
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM consultations c
      WHERE c.id = consultation_recordings.consultation_id
      AND (
        auth.uid() IN (SELECT id FROM admin_users)
        OR c.faculty_id = auth.uid()
      )
    )
  );

-- Create policy: Only admins can insert recordings
CREATE POLICY "Enable insert for system" ON consultation_recordings
  FOR INSERT WITH CHECK (true);

-- Create policy: Only admins can delete recordings
CREATE POLICY "Enable delete for authorized users" ON consultation_recordings
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM admin_users
      WHERE id = auth.uid()
    )
  );
